# Generated by Django 6.0.3 on 2026-04-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='status',
            field=models.CharField(default='Em Desenvolvimento', max_length=20),
        ),
    ]
