# Generated by Django 6.0.3 on 2026-04-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_projeto_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadospessoais',
            name='telefone',
            field=models.CharField(default=83996311626, max_length=15),
            preserve_default=False,
        ),
    ]
