# Generated by Django 6.0.3 on 2026-04-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dadospessoais_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadospessoais',
            name='nome_social',
            field=models.CharField(default='José Nickolas', max_length=50),
        ),
    ]
