# Generated by Django 6.0.3 on 2026-04-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dadospessoais_nome_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadospessoais',
            name='idade',
            field=models.IntegerField(default=20),
        ),
    ]
