# Generated by Django 6.0.4 on 2026-04-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dadospessoais_idade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=50)),
                ('duracao', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('link_certificado', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
