# Generated by Django 6.0.4 on 2026-04-21 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_certificado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='imagem',
        ),
    ]
