# Generated by Django 6.0.4 on 2026-04-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_projeto_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('icone_url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='idade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='nome_social',
            field=models.CharField(max_length=50),
        ),
    ]
